version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run:
          name: CI Build
          command: script/cibuild
          environment:
            RUBOCOP_TEST: true
            RSPEC_TEST: true
