name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6]
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: |
        ruby -v
    container:
      image: ruby:${{matrix.ruby-version}}
